env:
  OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
  OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
jobs:
  build:
    env:
      JAVA_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    name: Build on JDK ${{ matrix.java_version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java_version }}
        server-id: sonatype-nexus-snapshots
        server-password: OSS_PASSWORD
        server-username: OSS_USERNAME
    - continue-on-error: true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: ${{ env.SONAR_TOKEN != null && env.SONAR_TOKEN != '' && matrix.java_version
        == '17' }}
      name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      name: Run tests
      run: ./mvnw -V -B -ntp -ff verify jacoco:report
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: ${{ env.SONAR_TOKEN != null && env.SONAR_TOKEN != '' && matrix.java_version
        == '17' }}
      name: Static Analysis (Sonar)
      run: ./mvnw -B -ntp -ff org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
    - continue-on-error: true
      if: matrix.java_version == '11'
      name: Release Snapshot
      run: ./mvnw -V -B -ntp -ff deploy
    strategy:
      fail-fast: false
      matrix:
        java_version:
        - '8'
        - '11'
        - '17'
        - '21'
name: Main Build
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
